### ISSUE TITLE
Rabbit Stew cannot be crafted

### ISSUE THREAD

**Issue by saltyseadoggo** [DewittSmith/BonAppetit#3]
In the latest release of the mod, rabbit stew cannot be crafted. Delving into the data/minecraft/recipes folder reveals that, while the overrides for the vanilla recipes to prevent them from being used are present, the new recipe is missing, so no recipe is found for the stew.
The replacement rabbit stew recipe is still in my fork, so did you perchance remove it?

**Comment by Disketaa** [comment]
Fixed. Thanks!
