### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [DewittSmith/BonAppetit#9]
The mod still doesn't work on the server, I get a crash when turning on the server. There is no such problem on the client.

I have previously reported this bug, but the bug was never fixed. #1 

MC version: **1.16.4**
Fabric API: **0.29.3**
Mod version: **0.8.5** and **0.8.3.3**

Full logs:
- [0.8.5 latest.log](https://github.com/DewittSmith/BonAppetit/files/5816140/latest.log)
- [0.8.3.3 latest.log](https://github.com/DewittSmith/BonAppetit/files/5816172/latest.log)

**Comment by DewittSmith** [comment]
It was fixed after first issue, but there appeared new problems. Fixed.
